.TH MYSTRCPY 3 "2024" "libmputils" "Library Functions"
.SH NAME
mystrcpy \- copy a string
.SH SYNOPSIS
.nf
.B #include "../include/mystrfunctions.h"
.PP
.BI "int mystrcpy(char *" dest ", const char *" src );
.fi
.SH DESCRIPTION
.B mystrcpy
function copies the string pointed to by
.IR src ,
including the terminating null byte (\\0), to the buffer pointed to by
.IR dest .
The strings may not overlap, and the destination string
.I dest
must be large enough to receive the copy.
.SH RETURN VALUE
The number of characters copied (excluding the null byte).
.SH AUTHOR
Muhammad Arif Butt
